### ISSUE TITLE
Problem releasing new version

### ISSUE THREAD

**Issue by meeber** [chaijs/type-detect#109]
Merging #91 didn't trigger a release. Found this in the [travis logs](https://travis-ci.org/chaijs/type-detect/jobs/295118314):

> 6.95s$ travis-after-all && npm run semantic-release
> [travis-after-all] Job succeeded (40027526e0227d81659090077756bde5fb9776ff1d5e08fb38f991cd2a5144cc)
> [travis-after-all] Waiting for 427.2, 427.3, 427.4 and 427.5 to be done...
> [travis-after-all] Failed to parse JSON from "https://api.travis-ci.org/jobs/295118317".
> Error: Cannot read property 'indexOf' of null

**Comment by keithamus** [comment]
https://github.com/chaijs/type-detect/pull/108 should fix this
