### ISSUE TITLE
Issues running tests locally

### ISSUE THREAD

**Issue by meeber** [chaijs/type-detect#110]
On my lightweight AWS EC2 instance with no browsers installed, it remains stuck at the following part when running the test suite with the new build process and plumbing in place:

> > type-detect@ test:browser /opt/code/type-detect
> > karma start --singleRun=true
> 
> 02 11 2017 21:33:01.012:INFO [framework.detect-browsers]: The following browsers were detected on your system: []
> 02 11 2017 21:33:01.050:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
>

**Comment by keithamus** [comment]
Hmm, so it looks like `karma-detect-browser` detected no browsers! I wonder if we can get it to fail if it detects none.

**Comment by keithamus** [comment]
@meeber it looks like we could configure the `postDetection` function (https://github.com/litixsoft/karma-detect-browsers) to either `throw` or to perhaps push in a non-browser (like... *sigh*... phantomjs). What do you think is best? I'm leaning on throwing, but do you think thats a bit harsh for environments without an installed browser?

**Comment by meeber** [comment]
I'm okay with it throwing since it happens at the end. If it's possible to warn and skip, that'd be okay too.

**Comment by keithamus** [comment]
@meeber care to try out 53c6fab6bd33aa93fa285c67a8cf35f65c59538b ? It should fix this issue.

**Comment by meeber** [comment]
Yup that worked:

> type-detect@ test:browser /opt/code/type-detect
> karma start --singleRun=true

> 02 11 2017 23:16:47.013:INFO [framework.detect-browsers]: The following browsers were detected on your system: []
> **********************************
> **************WARNING*************
> **********************************
> Karma has been unable to detect a browser on your system
> Karma will now exit(0). If you have a browser you'd like to test
> please run `env KARMA_MANUAL=1 karma`, and manually load up a browser

**Comment by meeber** [comment]
Fixed by #108
