### ISSUE TITLE
Build failing due to sauce tunnel issue

### ISSUE THREAD

**Issue by meeber** [chaijs/type-detect#111]
Sauce is reporting the error as being "Your test errored. No active tunnel found for identifier 1509755873974". That number looks to be milliseconds since epoch from [here](https://github.com/chaijs/type-detect/blob/49b70623d24aa93e2a35f108ff1af0fc71750e7a/karma.conf.js#L5), but I think what we need is the Travis job number from [here](https://github.com/chaijs/type-detect/blob/49b70623d24aa93e2a35f108ff1af0fc71750e7a/karma.conf.js#L25)?

**Comment by vieiralucas** [comment]
That looks correct

https://docs.travis-ci.com/user/sauce-connect/
> To allow multiple tunnels to be open simultaneously, Travis CI opens a Sauce Connect Identified Tunnel. Make sure you are sending the TRAVIS_JOB_NUMBER environment variable when you are opening the connection to Sauce Labs’ selenium grid, as the desired capability tunnel-identifier, or it will not be able to connect to the server running on the VM.
