### ISSUE TITLE
4.0.4 contains breaking change to ES6 modules

### ISSUE THREAD

**Issue by lennym** [chaijs/type-detect#118]
type-detect@4.0.4 uses ES6 modules in its `main` which causes it to throw the following error when run in node:

```
export default function typeDetect(obj) {
^^^^^^
SyntaxError: Unexpected token export
```

I assume this was accidental, since it's a *massive* breaking change in a patch release making chai unusable. You may wish to unpublish 4.0.4.

**Comment by keithamus** [comment]
We'll get this fixed ASAP.

**Comment by keithamus** [comment]
4.0.5 will be released in the next few minutes, which should fix this.
