### ISSUE TITLE
v4.0.4 minor but breaking changes on node 6

### ISSUE THREAD

**Issue by danlevan** [chaijs/type-detect#119]
```
export default function typeDetect(obj) {
^^^^^^
SyntaxError: Unexpected token export
```

We are still using node6 LTS and this morning, our tests (using chai) fails with this error.

**Comment by bittrance** [comment]
This issue is currently blocking deploys in our projects based on Docker with Alpine 3.6 nodejs-current -> 7.10.1.

**Comment by keithamus** [comment]
👍 We'll get this fixed, thanks.

**Comment by dylansmith** [comment]
Temporary workaround is possible: `npm i type-detect@4.0.3`

**Comment by keithamus** [comment]
`4.0.5` will be released in the next few minutes, which should fix this.

**Comment by danlevan** [comment]
Thanks for the quick fix 🥇

**Comment by MichaelKohler** [comment]
@keithamus 4.0.5 doesn't work here. Have you forgotten your build step? ;)
