### ISSUE TITLE
'Unexpected token export' Issue using chai in last release

### ISSUE THREAD

**Issue by wiseolddj** [chaijs/type-detect#121]
It looks like there is a breaking change. We have locked our version on chai but we now get the following error:

```
/src/node_modules/type-detect/index.js:49
export default function typeDetect(obj) {
^^^^^^

SyntaxError: Unexpected token export
```

**Comment by keithamus** [comment]
We'll ge tthis fixed asap.

**Comment by keithamus** [comment]
`4.0.5` will be released in the next few minutes, which should fix this.
