### ISSUE TITLE
requiring 4.0.4 leads to SyntaxError

### ISSUE THREAD

**Issue by illuxio** [chaijs/type-detect#122]
With the update from version 4.0.3 to 4.0.3 I cannot require "type-detect/index.js" any longer, because it complains about a SyntaxError.

```node_modules/type-detect/index.js:49
export default function typeDetect(obj) {
^^^^^^
```

**Comment by vieiralucas** [comment]
Hello @illuxio, v4.0.5 just got released and should fix that. Sorry for the mess

**Comment by illuxio** [comment]
Yes, I can confirm that it fixed the issue :+1:
