### ISSUE TITLE
Latest version breaks in nodejs

### ISSUE THREAD

**Issue by tanqhnguyen** [chaijs/type-detect#124]
https://github.com/chaijs/type-detect/blob/master/rollup.conf.js#L17 seems to break `type-detect` when running in nodejs environment because it generates

```
export default function typeDetect(obj) {
```

which is not supported by nodejs

**Comment by danlevan** [comment]
Fixed in `4.0.5`

**Comment by MichaelOrtho** [comment]
I saw that error in 4.0.5 but after trying to repeat it in new folder it is now showing it. Maybe it was some cache issue. If this repeats I will raise it again. Thank you!

https://github.com/chaijs/type-detect/issues/126
