### ISSUE TITLE
v4.0.6 breaks node tests that manipulate global.window

### ISSUE THREAD

**Issue by pgoldrbx** [chaijs/type-detect#133]
Changes introduced by https://github.com/chaijs/type-detect/pull/129

After switching to use `window` rather than `globalObject`, tests running in node with a mock `window` (e.g. jsdom) will fail when manipulating (or deleting) `global.window` at runtime. I don't know how common this is, but it is a quick way to test modules intended to run on both client and server.

```sh
mocha --require config.js test
```
```js
// config.js
const { JSDOM } = require('jsdom');
const { window } = new JSDOM('<!doctype html><html><body></body></html>');
global.window = window;
```
```js
// test/foo.spec.js
const { expect } = require('chai');

describe('simplified example', function () {
  it('should perform assertions in a browser-like environment', function () {
    expect({}).to.eql({});
  });

  it('should not break when window removed', function () {
    global.window = null; // ideally reset afterward
    expect({}).to.eql({}); // boom!
    // TypeError: Cannot read property 'location' of null
    //  at typeDetect (node_modules/type-detect/type-detect.js:127:47)
  });
});
```

This could be avoided by `chai` users with greater care (and clear documentation), but I believe it was likely an unintended side effect of the changes made in #129.

Possible solutions:
- Accept the new behavior but revert to patch and then republish as a breaking change with clear documentation around expected behavior.
- Evaluate environment at runtime in the `typeDetect` function, rather than cached in the module. This will be slightly less efficient but will be accurate. It also raises the question as to whether all feature checks should be evaluated on every call as well.
- Other?

**Comment by meeber** [comment]
@pgoldrbx Thanks for the issue. My opinion is that this is a problem with caching the environment checks, so I lean toward the second solution you suggested. @keithamus?

**Comment by keithamus** [comment]
*sigh*. Okay, agreed the second solution sounds best.

> It also raises the question as to whether all feature checks should be evaluated on every call as well.

This literally only comes up with `window` because of JSDom. We have never run into an issue caching existence of the other values. I'm averse to refactoring the other values until someone can demonstrate a (real life) need for it.

**Comment by pgoldrbx** [comment]
That makes sense to me. I'm happy to PR if you'd like, or i can defer since this code has been modified a few times.

**Comment by meeber** [comment]
@pgoldrbx About to push a PR, thanks for the offer though!
