### ISSUE TITLE
Clarify usage in browser case

### ISSUE THREAD

**Issue by bricksphd** [chaijs/type-detect#139]
When importing type-detect in the browser, the function is called 'typeDetect'

If the usage examples are followed as-is, the browser will throw an error indicating that type() is not defined. 

In order to run the examples as written in the browser, the user should declare a variable type that refers to typeDetect(). An alternative would be to provide another set of browser-specific examples using typeDetect() instead of type(), but I think that would be overly verbose and confusing.

**Comment by keithamus** [comment]
Hey @bricksphd thanks for the issue!

I see you've got a commit which fixes the Readme, but it's raised as a PR against your fork. If you make a PR against this repository I'll happily accept & merge it 🙂

**Comment by bricksphd** [comment]
Sorry :) I think I did it the right way now.

**Comment by keithamus** [comment]
Thanks for this @bricksphd! Awesome work 🙂
