### ISSUE TITLE
ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by LeonardoGentile** [chaijs/type-detect#98]
Hello,
I'm using Webstorm to run Mocha tests (on react components) using Chai together with Enzyme, Sinon and Sinon-chai.

I'm doing something like this: 
`expect(ChildSpy).to.have.been.calledWithMatch({a:'a', b: 'b'}); ` that basically is the same as saying:
`sinon.assert.calledWith(ChildSpy, sinon.match({a:'a', b: 'b'}));`.

However I use it I receive and exception from this packages, exactly [from this line](https://github.com/chaijs/type-detect/blob/master/index.js#L159): 

```
ReferenceError: HTMLElement is not defined
    at typeDetect (node_modules/type-detect/index.js:159:24)
    at typeOf (node_modules/sinon/lib/sinon/util/core/typeOf.js:6:12)
    at Object.match (node_modules/sinon/lib/sinon/match.js:103:16)
    at Context.<anonymous> (test/main.js:106:45)
``` 

Apparently the `HTMLElement` used in this function is not defined. 
Does that depend on the node version or maybe was this package conceived to run in the browser and not in node?

```
if (obj instanceof HTMLElement && obj.tagName === 'BLOCKQUOTE') {
    return 'HTMLQuoteElement';
}
```

Maybe there is a check somewhere to understand if we are in a browser or not but I could have make things difficult to check because before starting my tests I do this:

```
// Setup for enzyme: http://airbnb.io/enzyme/docs/guides/jsdom.html
const doc = jsdom.jsdom('<!doctype html><html><body></body></html>', {
  url: 'http://localhost'
});
const win = doc.defaultView;

// Setup for react test-utils 'renderIntoDocument':
// it requires window, window.document and window.document.createElement
// globally available before you can import React
global.document = doc;
global.window = win;
global.navigator = win.navigator;
```

So type-detect believes is in a browser when in fact it's not? 🤔

**Comment by LeonardoGentile** [comment]
Yes, probably I'm tricking it into believing it I'm in a browser, I guess line 9 explains it:

`var isDom = 'location' in globalObject && 'document' in globalObject;`

But I don't know how I could solve this...I defined those globals for a reason

**Comment by LeonardoGentile** [comment]
Temp fix until #91 will be solved:

```
// [...] continues from above code
global.HTMLElement = win.HTMLElement;
```

**Comment by ljharb** [comment]
You could probably solve it by explicitly checking the things you use, instead of inferring their existence from other related things.

**Comment by cmdelatorre** [comment]
@LeonardoGentile that hack in the tests configuration boilerplate fixed it for me. Thanks.

**Comment by titse** [comment]
This worked for me when i declared JSDOM in a separate file and use require with mocha
```
var jsdom = require('jsdom');
// Create a fake DOM for testing with $.ajax
global.window = new jsdom.JSDOM().window;
global.document = window.document;
global.HTMLElement = window.HTMLElement;
```

**Comment by spearmootz** [comment]
the solution above should work, but chai is not a library exclusive to the browser but also node therefore the workaround above should not be required at all.

**Comment by titse** [comment]
I was testing with multiple files that required JSDOM. There was a problem with jQuery's window only being called once. I had to fix that error first and this error popped up. The above solution would work if they working in combination of Mocha+Chai+Sinon+JSDOM.

**Comment by Petercopter** [comment]
@titse This works for me. I'm busy upgrading chai, enzyme, and chai-enzyme, and adding this to the Mocha config did the trick for me. 🍺  👍  🚀
